name: Continuous Integration

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    name: Build on ${{ matrix.os }}, using node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ ubuntu ]
        node-version: [ 10.x, 12.x, 14.x ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build

  test:
    needs: build
    name: Test on ${{ matrix.os }}, using node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ ubuntu ]
        node-version: [ 10.x, 12.x, 14.x ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test
